---
- name: redhat | Installing Kata Containers Pre-Reqs
  yum:
    name: ["yum-utils"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Adding Kata Containers Repo
  yum_repository:
    name: kata_containers
    description: Branch project for Kata Containers branch master ({{ 'CentOS_' + ansible_distribution_major_version }})
    baseurl: "{{ kata_containers_redhat_repo }}"
    enabled: true
    gpgcheck: true
    gpgcakey: "{{ kata_containers_redhat_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Kata Containers
  yum:
    name: ["kata-runtime", "kata-proxy", "kata-shim"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"
